### ISSUE TITLE
Frog4-orchestrator connection with the frog4-datastore

### ISSUE THREAD

**Issue by farmanullahcs** [netgroup-polito/frog4-orchestrator#13]
The Frog4-orchestrator still have template API and many functions used for the datastore, So this code should be removed from the Frog4-orchestrator.

**Comment by gabrielecastellano** [comment]
Closed yesterday with b0f7885208d8a69ca793a96d99f2f0b284e42c70

**Comment by ivanocerrato** [comment]
@farmanullahcs , what was the code that you showed me today? Did you see on your branch, which may not be sync with the master?

I ask this because I actually saw with @farmanullahcs some code related to the interaction with the detastore. For instance, he showed me that the frog-orchestrator has some rest API that can be used for requests related to the datastore.

**Comment by farmanullahcs** [comment]
closed with [ba16693](https://github.com/netgroup-polito/frog4-orchestrator/commit/ba16693ec5262bfe5b733d62f86316f089782c75)

**Comment by ivanocerrato** [comment]
> closed with ba16693

Actually @gabrielecastellano says that the issue was already closed :) So, what is going on :face_with_thermometer:  ?

**Comment by farmanullahcs** [comment]
@gabrielecastellano Can you please check the commit [ba16693](https://github.com/netgroup-polito/frog4-orchestrator/commit/ba16693ec5262bfe5b733d62f86316f089782c75) there was template api and many functions used for the datastore.
